### ISSUE TITLE
Can't make this work in H19, Py3.7

### ISSUE THREAD

**Issue by musamaster** [Ozeuth/Python-Houdini-Plugin-for-Tensorflow-Smoke-Stylization#3]
Can you please let us know if we can make this work in H19 py3.6? We can't install the tensorflow version you reccomended in the webpage with 3.7. The HDA crashes immediately when we try with with the latest tensor flow. Thank you.

**Comment by Ozeuth** [comment]
Hello, I'm currently very busy with other work but I'll take a look into this later. I am considering revamping the entire plugin to work with later versions of Houdini, as a lot of the current pipeline is obsolete. Unfortunately, this will take quite a bit of time.

**Comment by musamaster** [comment]
Thank you so much!

**Comment by musamaster** [comment]
Also, let me know if I can be of help.

**Comment by lookbothways** [comment]
Hi, I installed Tensorflow 1.15 because 1.12 was unavailable:

```
curl https://bootstrap.pypa.io/get-pip.py -o C:/hython/get-pip.py
hython C:/hython/get-pip.py
hython -m pip install scipy
hython -m pip install matplotlib
hython -m pip install scikit-image 
hython -m pip install tensorflow==1.15
```

(On a laptop with piggybacked RTX, so trying TF CPU first.)

I can get the demo_py3 file to open by saving a version pre-tensorflow install with no python in the python node, then pasting it in. The error I get is: 

`AttributeError: module 'tensorflow._api.v1.random' has no attribute 'set_seed'`

Any ideas?

**Comment by lookbothways** [comment]
Hi - progress update: I can get the demo_py3 file to run with no errors in its python node. 

I was getting this error: 
`Cannot convert a symbolic Tensor (meshgrid/Size:0) to a numpy array.`

Stackexchange here https://stackoverflow.com/questions/58479556/notimplementederror-cannot-convert-a-symbolic-tensor-2nd-target0-to-a-numpy

Indicated it was numpy that was breaking it, so I downgraded numpy:

`pip install numpy==1.19.5`

The results when rendered are very voxelly and jittery, but no errors (Hurrah!). I can plug a new pyro sim into it and it works - however, when I try to follow the setup instructions on a brand-new scene I get stuck. 
Is the setup in the image below correct? The same pyro_import node works in the demo_py3 file (the paths to the sparse default sim are the same). 

The error I'm getting is: 

`Invalid source [/obj/pyro_import/Smoke_Stylizer_Oz1/get_vect_field](node:/obj/pyro_import/Smoke_Stylizer_Oz1/get_vect_field)
Error: Python error: Traceback (most recent call last):
File "<stdin>", line 249, in <module>
File "hou.session", line 92, in send_data
File "hou.session", line 98, in help_send
OSError: [Errno 22] Invalid argument
.`

This is progress regardless. Thank you for putting this together :-) 

![not_working](https://user-images.githubusercontent.com/17749921/164313860-b3d41342-a561-4348-bfd7-8a4e6e0e16cc.JPG)


(The result is the same if I don't have /python.exe explicitly defined)

**Comment by Ozeuth** [comment]
Hey there,
I'm glad you found the py3 demo- I would have suggested you try it, but was certain it was too buggy to be used. Really impressed you managed to troubleshoot it.
I can't figure out what the issue in your setup is immediately, but I will test it out this weekend and let you know :)

**Comment by lookbothways** [comment]
Thank you. It'd be great this would work without a huge overhaul to 2.0 etc. 
If it helps, my versions of things are (retrieved via __version__, some were unknown):

 ['os', 'datetime', 'skimage', 'sys', 'hou', 'glob', 'numpy', 'json', 'matplotlib', 's
hutil', 'tensorflow', 'imageio', 'argparse']

skimage 0.19.2
numpy 1.19.5
json 2.0.9
matplotlib 3.5.1
tensorflow 1.15.0
imageio 2.6.1
argparse 1.1

Happy to help if I can.

**Comment by lookbothways** [comment]
I have to get on with other things, but it seems to be an issue with hou.session, pOpen and stdin/out not being able to send/receive. I started swapping out stdins for process.communicate (as a stab in the dark) but need to stop now.

**Comment by lookbothways** [comment]
I've dug this up again as I'm still keen to try it out. I'm having the same issue as before:

`File "<stdin>", line 249, in <module> File "hou.session", line 92, in send_data File "hou.session", line 98, in help_send OSError: [Errno 22] Invalid argument .`

I'm convinced it's to do with subprocess not talking to Houdini properly, but not good enough at python to work out if this is true. 
@Ozeuth What are your thoughts?
